par("mfrow" = c(2,2))
par("mar" = c(5,5,2,2))
plot(uu$DateTime, uu$Global_active_power, type = "l", ylab = "Global Active Power", xlab = "")
plot(uu$DateTime, as.numeric(uu$Voltage), type = "l", ylab = "Voltage", xlab = "Datetime")
plot(uu$DateTime, uu$Sub_metering_1, type = "l", col = "black", ylab = "Energy sub metering", xlab = "")
lines(uu$DateTime, uu$Sub_metering_2, type = "l", col = "red", ylab = "", xlab = "")
lines(uu$DateTime, uu$Sub_metering_3, type = "l", col = "blue", ylab = "", xlab = "")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1, lwd = 2.5, col = c("black", "red", "blue"), cex = 0.1)
plot(uu$DateTime, as.numeric(uu$Global_reactive_power), type = "l", ylab = "Global_reactive_power", xlab = "Datetime")
dev.copy(png, file = "plot4. png")
dev.off()
