rr<-read.table("household_power_consumption.txt", header = TRUE, sep = ";")
library(lubridate)
tt<- dmy(rr$Date)
yy<- cbind(rr, tt)
library(dplyr)
uu<- filter(yy, tt %in% c(as.Date("2007-02-01"), as.Date("2007-02-02")))
par("mfrow"= c(1,1))
uu<- uu %>% mutate(DateTime = paste(Date, Time, sep = " "))
uu$DateTime <- as.POSIXct(uu$DateTime, format = "%d/%m/%Y %H:%M:%S")
plot(uu$DateTime, uu$Global_active_power, type = "l", ylab = "Global Active Power", xlab = "")
dev.copy(png, file = "plot2. png")
dev.off()
