rr<-read.table("household_power_consumption.txt", header = TRUE, sep = ";")
library(lubridate)
tt<- dmy(rr$Date)
yy<- cbind(rr, tt)
library(dplyr)
uu<- filter(yy, tt %in% c(as.Date("2007-02-01"), as.Date("2007-02-02")))
par("mfrow"= c(1,1))
uu<- uu %>% mutate(DateTime = paste(Date, Time, sep = " "))
uu$DateTime <- as.POSIXct(uu$DateTime, format = "%d/%m/%Y %H:%M:%S")
plot(uu$DateTime, uu$Sub_metering_1, type = "l", col = "black", ylab = "Energy sub metering", xlab = "")
lines(uu$DateTime, uu$Sub_metering_2, type = "l", col = "red", ylab = "", xlab = "")
lines(uu$DateTime, uu$Sub_metering_3, type = "l", col = "blue", ylab = "", xlab = "")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1, lwd = 2.5, col = c("black", "red", "blue"), cex = 0.3)
dev.copy(png, file = "plot3. png")
dev.off()
