rr<-read.table("household_power_consumption.txt", header = TRUE, sep = ";")
library(lubridate)
tt<- dmy(rr$Date)
yy<- cbind(rr, tt)
library(dplyr)
uu<- filter(yy, tt %in% c(as.Date("2007-02-01"), as.Date("2007-02-02")))
par("mfrow"= c(1,1))
hist(as.numeric(uu$Global_active_power), xlab = "Global Active Power (kilowatts)", ylab = "Frequency", main = "Global Active Power", col = "red")
dev.copy(png, file = "plot1.png")
dev.off()
